"""Criado user_name

Revision ID: 0593c9cda1b8
Revises: 21294b3c2843
Create Date: 2023-08-02 23:59:02.295488

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0593c9cda1b8'
down_revision = '21294b3c2843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
